### ISSUE TITLE
Not showing functional icons

### ISSUE THREAD

**Issue by wheatdog** [lxqt/pavucontrol-qt#126]
##### Expected Behavior

Showing functional icons.

##### Current Behavior

![image](https://user-images.githubusercontent.com/7741908/54817825-ca286980-4cd2-11e9-9226-123d9da7e6b2.png)
Not showing mute icons.

##### Steps to Reproduce (for bugs)

1. `pacman -S pavucontrol-qt`
2. run pavucontrol-qt

##### System Information

* Distribution & Version: Arch Linux
* Kernel: 5.0.2-arch1-1-ARCH
* Qt Version: 5.12.2-1
* libqtxdg Version: none
* lxqt-build-tools Version: none
* Package version: 0.14.1

**Comment by tsujan** [comment]
There can be a problem about icons on your system.

![icons](https://user-images.githubusercontent.com/981076/54819666-44002900-4cba-11e9-800f-1a93313864ff.png)

**Comment by wheatdog** [comment]
@tsujan, you are right! Thanks! I follow the instruction in https://wiki.archlinux.org/index.php/Qt#Configuration_of_Qt5_apps_under_environments_other_than_KDE_Plasma and everything is fine now.

**Comment by tsujan** [comment]
Good to know that your problem is fixed.

LXQt manages icons, like KDE does, but you could use its libraries outside LXQt too (I guess your screenshot was taken outside LXQt). For example, you could install some LXQt components -- especially `lxqt-qtplugin` -- and set the environment variable `QT_QPA_PLATFORMTHEME` to `lxqt`. In that way, Qt will be handled in the best way.

**Comment by raffaem** [comment]
> @tsujan, you are right! Thanks! I follow the instruction in https://wiki.archlinux.org/index.php/Qt#Configuration_of_Qt5_apps_under_environments_other_than_KDE_Plasma and everything is fine now.

The new link is https://wiki.archlinux.org/title/Qt#Configuration_of_Qt_5_applications_under_environments_other_than_KDE_Plasma.

Basically just run:
```
XDG_CURRENT_DESKTOP=GNOME pavucontrol-qt
```

or

```
XDG_CURRENT_DESKTOP=KDE pavucontrol-qt
```

**Comment by thahn01** [comment]
Under debian trixie this seems to be a qt6 application.
Mute icon is shown under Plasma.
Workaround with

**Comment by luis-pereira** [comment]
> Under debian trixie this seems to be a qt6 application. Mute icon is shown under Plasma, but not with lxqt 2.1 and lxqt 2.2 (debian sid)
> 
> Workaround with XDG_CURRENT_DESKTOP=KDE pavucontrol-qt does not help

Post values of the  `XDG_CURRENT_DESKTOP` and `QT_QPA_PLATFORMTHEME` .
What happens when using the Oxygen icon theme ?

**Comment by thahn01** [comment]
env|egrep 'XDG_CURRENT_DESKTOP|QT_QPA_PLATFORMTHEME'
QT_QPA_PLATFORMTHEME=lxqt
XDG_CURRENT_DESKTOP=LXQt

If I change the Appearance to Oxygen, the icon is there.
