### ISSUE TITLE
wrongSpinBoxMaxRange

### ISSUE THREAD

**Issue by damianatorrpm** [lxqt/pavucontrol-qt#128]
Qt version supports setting latency offset only to 100ms. It must be like gtk version any int value #wrongSpinBoxMaxRange
PS: my headphones need ~250 ms to work correctly

**Comment by sandsmark** [comment]
https://github.com/sandsmark/pavucontrol-qt/commit/986a626050a66c46a1bbf8f537ec3512840a4193 fairly simple fix

**Comment by tsujan** [comment]
→ https://github.com/lxqt/pavucontrol-qt/issues/258
