### ISSUE TITLE
hangs with Establishing connection to Pulseaudio

### ISSUE THREAD

**Issue by jaccc** [lxqt/pavucontrol-qt#136]
##### Steps to Reproduce (for bugs)

1. run XFCE and Pulseaudio in system-wide mode
2. 
3. 
4. 

##### System Information

* Distribution & Version: Gentoo
* Kernel: 
* Qt Version: 5.12.3
* libqtxdg Version: 
* lxqt-build-tools Version: 
* Package version:

**Comment by esalanguerra** [comment]
archlinux and bspwm
