### ISSUE TITLE
WishList: TrayIcon

### ISSUE THREAD

**Issue by ghost** [lxqt/pavucontrol-qt#15]
Icon tray option for pavucontrol would be great!

**Comment by palinek** [comment]
What it should be good for? Just minimizing to tray?

**Comment by GinoM** [comment]
Minimizing to tray, basic Icons support like
* is master muted
* maybe 3 step gradation of speaker volume represented in icon (if you want to get really fancy)
* integration with globalkeys for Mediakey keyboard to map volume buttons to Mute/unmute and VolUp/VolDown

**Comment by palinek** [comment]
All these features are incorporated in the `volume-plugin` of lxqt-panel => so I don't think anyone from LXQt team would want to implement those into the pavucontrol-qt.

Of course anyone can step in and develop such functionality.

**Comment by GinoM** [comment]
Ah, ok, I run lxqt but I do not use lxqt-panel, so that's why a generic tray icon interests me, it could be used with any systray compatible panel

**Comment by ypnos** [comment]
I believe this feature is out-of-scope for pavucontrol. Generic tray icons and desktop integrations to control main volume already exist and run independently of pavucontrol, just like the lxqt-panel plugin.

I suggest you have a look at:

- `pasystray` for the tray icon, very feature-rich, including obviously volume controls and launching pavucontrol
- `ponymix` for media-key bindings, it provides the handy increase, decrease, mute commands
