### ISSUE TITLE
Can't hear anything every 4 minutes

### ISSUE THREAD

**Issue by TeoColuccio** [lxqt/pavucontrol-qt#155]
I just installed Debian 10 lxqt and the computer is doing very well.  Except for the fact of a problem with the audio.  In practice very often (too much), while I am correctly reproducing an audio, suddenly, I don't hear anything anymore.  The only way to solve this is to open the pulseaudio mixer, set the output on the headphones, and then reset it to the PC speakers. The problem is that it happens every 3/4 minutes, far too often.

**Comment by tsujan** [comment]
You didn't give us any useful info. What you see isn't reproducible and can have various causes outside LXQt.

BTW, Debian's LXQt is outdated.
