### ISSUE TITLE
Enable wordwrap on error message when connection fails

### ISSUE THREAD

**Issue by SGOrava** [lxqt/pavucontrol-qt#165]
When it failts to connect to PA it shows a long message about it  which makes the window very big.

##### Expected Behavior

The error message is word-wrapped and the window has regular size.

##### Current Behavior

Error message makes the window very big

##### Possible Solution

Enable wordwrap

##### Steps to Reproduce (for bugs)

1. Disable PA (somehow)
2. Start this program
3. Observe

##### Context

I have 2 screens so I can find the other end of the window, but for smaller screens the window becomes too big

##### System Information

* Distribution & Version: Artix (rolling, about week or so old)
* Kernel: 5.8.10-artix1-1
* Qt Version: 5.15.1
* libqtxdg Version: 
* lxqt-build-tools Version: 
* Package version: 

##### Bonus
It would be nice to be able to copy the error message for easier debugging.

##### Preview
![Screenshot_2020-10-06_20-26-09](https://user-images.githubusercontent.com/6304663/95244453-41204700-0812-11eb-8721-9dc2dcf4ded0.png)

**Comment by tsujan** [comment]
The GUI supports horizontal scrollbars (https://github.com/lxqt/pavucontrol-qt/issues/99) but I guess the support is enabled only when no error happens. Should look into the code...

**Comment by SGOrava** [comment]
This showed up to me.
Even if it supports scrollbars reading long messages such as this one is hard for me.

**Comment by tsujan** [comment]
The fix is here: https://github.com/lxqt/pavucontrol-qt/pull/166. The text is wrapped and can be selected and copied by the mouse.

**Comment by SGOrava** [comment]
Thank you.

**Comment by tsujan** [comment]
Thank *you* for reporting.
