### ISSUE TITLE
Add it on lxqt groups on Arch Linux

### ISSUE THREAD

**Issue by gaetan1903** [lxqt/pavucontrol-qt#201]
When i install lxqt, i already forget the name of this application,

Can just add it Arch groups when i install with `pacman -S lxqt`

**Comment by shlyakpavel** [comment]
Why don't you address this to arch linux maintainers?

**Comment by tsujan** [comment]
Please report distro problems/requests to your distro.

**Comment by gaetan1903** [comment]
Sorry and thanks !
it's fixed now

https://bugs.archlinux.org/task/71790
