### ISSUE TITLE
Pavucontrol-qt opens in a floating window in i3

### ISSUE THREAD

**Issue by Anglodel** [lxqt/pavucontrol-qt#211]
Hi,

##### Expected Behavior

The window should, open in the current container layout : split, stacking or tabbed.

##### Current Behavior

At the moment, Pavucontrol-qt always opens in floating mode, which breaks i3 working method.

##### Possible Solution

X

##### Steps to Reproduce (for bugs)

1. Open Pavucontrol on an i3wm session
2. Then open Pavucontrol-qt
3. See that Pavucontrol-qt’s windows is in floating mode even if it was in another mode the last time it was closed, and that Gtk version open "normally".

##### Context

Pavucontrol-Qt appears over my already-opened windows and distracts me.  
It does not happen with the original Pavucontrol package (pavucontrol 5.0).
As pavucontrol-qt’s readme.md says "The software belongs to the LXQt project but its usage isn't limited to this desktop environment.", I permit myself to file this bug.

##### System Information

* Distribution & Version: Arch Linux x86_64 
* Kernel: 5.15.12-arch1-1
* Qt Version: Qt 5.15.2
* i3 version 4.20.1
* libqtxdg Version: 3.8.0-1
* lxqt-build-tools Version: 0.10.0-1
* Package version: 1.0.0-2

**Comment by tsujan** [comment]
Should be reported to i3.

**Comment by Anglodel** [comment]
That’s what I’ll do, then, but as it only happens with this Qt port of pavucontrol, I thought this was a bug to report here.

**Comment by tsujan** [comment]
> ... as it only happens with this Qt port of pavucontrol...

pavucontrol-qt's window is a `QDialog` and, according to your report, i3 can't handle `QDialog` correctly. That's a problem that should be fixed in i3.

**Comment by Anglodel** [comment]
It seems logical, with this explanation.
Thanks !
