### ISSUE TITLE
What do the three little square buttons in Output Devices tab do?  (I am confused by the UI)

### ISSUE THREAD

**Issue by atsaloli** [lxqt/pavucontrol-qt#218]
##### Expected Behavior

I'd like to be able to easily switch output from laptop headphones to external monitor, and back.

##### Current Behavior

I have to randomly click the three buttons a bunch of times until the sound comes on.

##### Possible Solution
Could you please explain how this works?

##### Context
I am having trouble switching between my built-in audio headphones jack and the speakers in my external monitor. I am confused by the UI.

The readme says the usage should be self-explanatory, but I don't get it. Help?

##### System Information

pavucontrol-qt 0.16.0
Qt        5.15.2

![screenshot](https://user-images.githubusercontent.com/508704/176500506-8fa6ac95-3042-4eee-8689-efed0ae05732.png)

**Comment by atsaloli** [comment]
I installed `pavucontrol` and it has 3 little square buttons too, but they have symbols in them:

![screenshot](https://user-images.githubusercontent.com/508704/176501024-c58c7278-967d-4877-91d2-98541451c331.png)

I still don't understand what this means.

**Comment by tsujan** [comment]
Either your active icon theme lacks `applications-multimedia`, `changes-prevent-symbolic` and `audio-volume-muted`, or you have a general problem with Qt apps. The problem isn't in pavucontrol-qt.

> I still don't understand what this means.

Those buttons have tool-tips.

**Comment by atsaloli** [comment]
@tsujan Thank you, that's helpful.

I am running Q4OS 4.8 (latest stable)  (https://q4os.org/), which is based on Debian, and I selected "minimal" install because I'm on a rural Internet connection, and apparently I'm missing the appropriate package.

Would you happen to know what Debian package or group of packages I would need to install to have an up to date and complete icon theme so these tool tips show up, please?

```
[:~] 100 $ sudo apt install applications-multimedia
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package applications-multimedia
$
```

I'm not familiar with icon theme management.

Also noted that I got an outdated pavucontrol-qt, thank you.

**Comment by tsujan** [comment]
> I am all set now

Oh, you solved your problem :)

**Comment by atsaloli** [comment]
@tsujan Got it, thank you very much!!  Thanks for looking into it!
