### ISSUE TITLE
Clicking volume meter shouldn't change volume by increments

### ISSUE THREAD

**Issue by dbedrenko** [lxqt/pavucontrol-qt#239]
##### Expected Behavior
If the volume is at 40% and I click on the meter where it would be 80%, the volume should change to 80% rather than to 45%.

##### Current Behavior
Volume moves at increments of 5% for every click.

##### Context
If I want to change the volume it's inconvenient to have to click, e.g. 6-15 times just to get it to the volume desired because of the 5% increments.
It's also inconvenient to locate the small volume slider itself, manage to click on it and drag it to the desired volume.
This is all made harder because the volume meter widget is so narrow that clicking needs to be very precise, and multiple clicks are required.

![image](https://user-images.githubusercontent.com/6204199/200420631-9e7e4fb0-d693-450a-b599-dd162dfc762e.png)

`pavucontrol` has the expected behaviour and is much easier to change volume on (no less because the slider widget is taller).

![image](https://user-images.githubusercontent.com/6204199/200420819-89bfeaa6-f65a-45cf-9bd0-42991e278e2d.png)

##### System Information                                                   --->
* Distribution & Version: ArchLinux 
* Package version: 1.2.0.1.g808b54b-1

**Comment by tsujan** [comment]
Short answer: Use the middle mouse button if the widget style you use is Fusion, Breeze,...

A little longer answer: It has nothing to do with pavucontrol-qt but with [QStyle::SH_Slider_AbsoluteSetButtons](https://doc.qt.io/qt-6/qstyle.html#StyleHint-enum), which is defined by the widget style. Most widget styles set it to the middle mouse button. As far as I know, only [Kvantum](https://github.com/tsujan/Kvantum) sets it to the left mouse button by default but lets it be configured.

**Comment by dbedrenko** [comment]
Thanks did not know about the middle mouse button. 

I understand you mean you cannot change the style in your code? I must change the Qt theme used on my machine?

**Comment by tsujan** [comment]
> I understand you mean you cannot change the style in your code?

It's possible with a hard-coded style. But apps shouldn't have hard-coded styles unless really necessary; otherwise they'll create a mess by breaking what's called "platform integration".

It's the widget style that should have an option for it. Sadly, most widget styles don't.
