### ISSUE TITLE
Icons not visible

### ISSUE THREAD

**Issue by raffaem** [lxqt/pavucontrol-qt#271]
##### Expected Behavior

I should see icons in the top right corner of audio devices, for "Muta audio", "Lock channels together", "Set as fallback actions"

##### Current Behavior

I don't see any icons:

![image](https://github.com/lxqt/pavucontrol-qt/assets/54762742/87662a70-9902-4b56-b7cc-c8d08d3b00cf)

##### Steps to Reproduce (for bugs)

1. Open pavucontrol-qt

##### Context

I have to change the default sink from laptop microphone to bluetooth headset microphone

##### System Information

* Distribution & Version: Arch Linux
* Kernel: 6.7.2
* Qt Version: 
* Package version: 
```
➜ pavucontrol-qt --version
pavucontrol-qt 1.4.0
Qt        5.15.11
```
* libqtxdg Version: It was not even installed as the Arch package doesn't depend on it. Manually installing it from official repo. Version libqtxdg-3.12.0-2. Bug still persists.
* lxqt-build-tools Version: Not installed (only needed if you compile from source?)

**Comment by stefonarch** [comment]
What icon theme are you using?
