### ISSUE TITLE
UI questions

### ISSUE THREAD

**Issue by waarmond** [lxqt/pavucontrol-qt#276]
This is not a bug report; pavucontrol-qt is compiling and working fine.

I've got 2 questions to the UI:
* Is a fullscreen window mode possible?
* May the bar from the screenshot be made thinner?

![peter](https://github.com/lxqt/pavucontrol-qt/assets/162583676/78700606-00f2-490e-8dc5-291b46136af9)

**Comment by tsujan** [comment]
> May the bar from the screenshot be made thinner?

It's drawn by the widget style and shouldn't be tampered with. This is how Breeze draws it:

![progressbar](https://github.com/lxqt/pavucontrol-qt/assets/981076/f5dd0fea-6819-4c8c-b544-82dd8990a3da)


In old version, a thin bar was enforced and caused bugs with some widget styles. The correct approach is leave widgets to be drawn by widget styles.

Please use [Discussions](https://github.com/lxqt/lxqt/discussions) for questions.
