### ISSUE TITLE
Now available: Qt5-based but working Cocoa/native implementation on Mac

### ISSUE THREAD

**Issue by RJVB** [lxqt/pavucontrol-qt#282]
I don't see how to do a PR request for incoporating a new branch so I'm using the issue tracker:

Pavucontrol-qt (pvcqt) works fine on Mac under X11 (requires a tweaked Qt build!) but it does not do anything at all when running natively because Qt's event dispatcher is not GLib based in that case.

Handling the events from `libpulse` thus requires the use of a `pa_threaded_mainloop`, which in turn means the code in `pavucontrolcc` and `mainwindow.cc` has to be adapted in order to ensure that a GUI calls are done from the main thread.

I've approached this the easiest way possible as libpulse event handling can be constrained by the GUI: calls to the mainthread are made with blocking calls to `QMetaObject::invokeMethod()`. This is on Qt 5.10 and up; for earlier versions an equivalent home-spun implementation is provided.

Qt have been very aggressive in dropping support for older versions of the Mac OS and those are exactly the versions where one expects to find more interest in running PulseAudio. I have thus done my implementation in Qt5 (I cannot use Qt6 myself) and have tested my code with Qt down to 5.6.3 . I used the last commit before the migration to Qt6.

NB: support for the native MSWin QPA should require little additional work.
NB2: the README mentions a dependency on `liblxqt` which is incorrect (at least for the original code I modified).

My fork: https://github.com/RJVB/pavucontrol-qt

**Comment by stefonarch** [comment]
So this should be a updated qt5-release or a different release at all?  We didn't plan actually to backport anything.

>NB2: the README mentions a dependency on liblxqt which is incorrect (at least for the original code I modified).

Thanks for the hint, indeed it looks like unneeded.

**Comment by RJVB** [comment]
On Tuesday August 06 2024 11:48:40 Standreas wrote:
>So this should be a updated qt5-release or a different release at all?  We didn't plan actually to backport anything.

It's really up to you. The way I see it my qt5-crossplatform branch could be included as such upstream. Or you could link to my repo. Or you could integrate my changes, which in essence are quite simple, in the Qt6 code.
The basic princple was simply to move every pa callback that interacts with the GUI into a custom QApplication class, and then invoke them from "stub" global callbacks that receive the QApplication instance as userdata and ensure that the corresponding class functions are executed on the main/GUI thread. The callbacks in mainwindow.cc were simple enough that I only modified how the MainWindow methods get called.
I'd do the porting to the Qt6 code myself but don't have that version installed and have not use for it for now ...

Re: backporting: I didn't backport anything in fact. I just took the last Qt5-based commit and worked from there. I didn't check if any new features, functionalities or fixes were introduced - yet. I'll do that sometime soonish.

I can understand you don't want to burden the code with if-Qt5-or-Qt6 conditionals (as far as those would be required) but I do think it's justified to have a straightforward way to obtain the latest existing sources that are buildable under Qt5. This is a nice little tool, and it's just that appreciable bit lighter on system resources than the GTk version is.

**Comment by tsujan** [comment]
> Now available: Qt5-based but working...

Quoted from https://github.com/lxqt/pavucontrol-qt/issues/284#issuecomment-2276183625:

"Please also note that LXQt doesn't support old versions: only the latest release is supported (currently 2.0.0), and any change to it will be made in git and appear in the next release."

> I don't see how to do a PR request for incoporating a new branch so I'm using the issue tracker:

If your mean two versions of pavucontrol-qt, we can't support that. But if you mean a manageable amount of code changes to the master branch, please make a PR.

In the first case, you could use https://github.com/lxqt/lxqt/discussions → `Show and tell` to reach more users.

**Comment by RJVB** [comment]
On Thursday August 08 2024 09:16:24 tsujan wrote:

>If your mean two versions of pavucontrol-qt, we can't support that.

You already have several branches in the repo that correspond to older releases. Adding one doesn't mean it needs to receive any more support. At best I'll be updating it if ever those would be required for future libpulse versions.
The only naggle is lxqt-build-tools, which claim a purely artificial requirement on a recent Qt version (remove that in v0.13.0 and they happily work with Qt 5.6 too).

>But if you mean a manageable amount of code changes to the master branch, please make a PR.

Define manageable?
