### ISSUE TITLE
Desktop entry file has to be adjusted

### ISSUE THREAD

**Issue by pmattern** [lxqt/pavucontrol-qt#3]
Keys `Name`, `GenericName` and `Comment` in desktop entry file `pcmanfm-qt.desktop` are stating the same values as in the corresponding file of the GTK version which will cause confusing results in menus and hence needs to be changed.

Posting an issue and not a PR as unsure how to do this best.
Of course the fact pavucontrol-qt is some kind of Qt counterpart of the GTK version has to be reflected.
That aside I do not think the upstream values make too much sense. E. g. given `GenericName` (rightly) states `Volume Control` this `Comment=Adjust the volume level` really comes as no suprise.

Maybe

```
Name=pavucontrol-Qt
GenericName=Volume Control
Comment=Volume control of PulseAudio sound server (Qt version)
```

or something like that?

**Comment by PCMan** [comment]
Ideally, one might not install both the gtk+ and qt versions at the same time.
For an LXQt user, "pavucontrol-qt" is much less informative than "Volume Control".
Since it's a Qt port, I reuse the original program name, but the naming is really bad.
As a user, I don't really know what "pavu" is.
In this case, "Volume control" is much better.

**Comment by pmattern** [comment]
> Ideally, one might not install both the gtk+ and qt versions at the same time.

While this is of course true in theory I'd bet that installing both in parallel will happen on a regular basis in practice. So I still think the naming should be such that they can be distinguished in menus.

**Comment by stefonarch** [comment]
IMO this is still an issue. It's  shown under "Audio" but should be shown also under "Settings", and it's much more than Volume control. Something like
```
..
Categories=AudioVideo;Audio;Settings;DesktopSettings;Mixer;Qt;
Name=Audio Settings
GenericName=Adjust volume levels and select audio devices
Comment=Adjust the volume levels and select devices
```

It doesn't work in the menu as duplicates are not shown I guess (adding a special condition?) but in lxqt-config:
![schermata-22 ago 09:13](https://user-images.githubusercontent.com/10681413/185862152-ad3ac958-9595-4def-ab2a-e80914f6b08d.png)

**Comment by tsujan** [comment]
Why didn't you make a PR?

> ... as duplicates are not shown I guess

They are. For example, Kvantum Manager is shown in two places.

**Comment by stefonarch** [comment]
With the above example not. But with `Categories=Qt;AudioVideo;Audio;Settings;DesktopSettings;LXQt` yes, didn't investigate why.  

> Why didn't you make a PR?

I wanted to discuss it first, where to show. Under "Other settings" or under "LXQt settings for example?

**Comment by tsujan** [comment]
> Where to show. Under "Other settings" or under "LXQt settings for example?

Personally, I have no special opinion; I just feel "Other settings" may be better.

> Which text?

It's mostly volume control. Maybe something like "PulseAudio Volume Control (Qt GUI)"

**Comment by stefonarch** [comment]
You won't use it for volume control except for the mic. Usually I open it to select and configure or switch  devices like HDMI, mics or headphones etc. 

I thought something generic like this:
```
Name=Audio Settings
GenericName=Adjust volume levels and select audio devices
Categories=Qt;AudioVideo;Audio;Settings;DesktopSettings;

```

**Comment by tsujan** [comment]
It's OK to me, expect for "Audio Settings". for two reasons: (1) it doesn't mention PulseAudio; and (2) since this utility doesn't cover all possible settings of  PulseAudio, "PulseAudio Settings" may be misleading too.

**Comment by stefonarch** [comment]
Ok, so let's stick with the original name: "PulseAudio Volume Control".

**Comment by stefonarch** [comment]
Hm, without "LXQt" in `Categories=` it can't be shown in Preferences, I tried fiddling with the menu but didn't manage to include it without removing `OnlyUnallocated`. So there are 2 options:
* Include it in LXQt settings
* Change menu files
```

<Include>
			<Or>
				<Category>Settings</Category>
				<Category>PackageManager</Category>
			</Or>
			<Filename>pavucontrol-qt.desktop</Filename>
		</Include>
		<Exclude>
			<Or>
				<Filename>lxqt-config.desktop</Filename>
				<Filename>pcmanfm-qt-desktop-pref.desktop</Filename>
			</Or>
			<Category>LXQt</Category>
		</Exclude>
```

Original menu file:
```
<OnlyUnallocated/>
		<Include>
			<Or>
				<Category>Settings</Category>
				<Category>PackageManager</Category>
			</Or>
			<Filename>pavucontrol-qt.desktop</Filename>
		</Include>
```

**Comment by tsujan** [comment]
> Hm, without "LXQt" in Categories= it can't be shown in Preferences

It seems that `AudioVideo` isn't compatible with Preferences; there may be a good reason for that (if so, I don't know what it is).

Anyway, I think we shouldn't enforce the opposite. Making an exception for this desktop entry in the menu file doesn't seem good either.

**Comment by tsujan** [comment]
The "good reason" mentioned above may be `<OnlyUnallocated/>` (which means "allow only those desktop entries that don't match other menus", I think). Haven't tested it though.

**Comment by stefonarch** [comment]
It's just about the way settings are separated. With the changed system (exluding  LXQt instead of using `OnlyUnallocated`) the menu looks the same but pavucontrol will be shown. It's not about AudioVideo incompatible.

**Comment by tsujan** [comment]
> With the changed system (exluding LXQt instead of using OnlyUnallocated) the menu looks the same but pavucontrol will be shown.

Yes, that's how `OnlyUnallocated` works.

> It's not about AudioVideo being incompatible.

Right. Any entry that shows up in another menu will be filtered out. In this case, it's because of `AudioVideo`.
