### ISSUE TITLE
No volume meter with some Qt styles.

### ISSUE THREAD

**Issue by wesbluemarine** [lxqt/pavucontrol-qt#75]
Choosing Windows Qt style, or others (Skulpture) , there is not real time volume indicator on top of the volume slider.

I thought it was an problem of Skulpture theme, so I've opened an issue [here](https://github.com/cfeck/skulpture/issues/1)

Quoting the dev answer of the developer:

> The pavucontrol-qt application hardcodes the height of the QProgressBar widget, see line 41 in https://github.com/lxqt/pavucontrol-qt/blob/master/src/minimalstreamwidget.cc
> 
> If it doesn't want to use QStyle::sizeFromContents(), then it could at least query the frame width using QStyle::pixelMetric(PM_DefaultFrameWidth).

##### System Information
* Distribution & Version: Opensuse Tumbleweed
* Kernel: Linux 4.18.5-1
* Qt Version: Qt 5.11.1
* libqtxdg Version: 3.1.0
#* Package version: 0.4.0

**Comment by tsujan** [comment]
That developer's answer is correct. I wanted to report the same thing but, instead, made some changes to [Kvantum](https://github.com/tsujan/Kvantum) for this situation to be tolerated by the widget style as far as possible (not 100% though).

In short, this is yet another example of a bad hard-coded style; see https://github.com/lxqt/lxqt/issues/1433#issue-287569590 (but forget about QML).

**Comment by sandsmark** [comment]
looked into fixing this more "properly" to try to keep a thin progress bar, but at least kvantum seems to "lie" about 
subElementRect for the progress bar parts, so can't really use that to see if we need to shrink it.

**Comment by tsujan** [comment]
> kvantum seems to "lie" about subElementRect...

Widget styles don't "lie" about sizes but *determine* them. See https://github.com/lxqt/lxqt/issues/1433#issue-287569590
