### ISSUE TITLE
Add trayicon functionality

### ISSUE THREAD

**Issue by tpruzina** [lxqt/pavucontrol-qt#83]
I would like to have this thing run on startup and be available from system tray icon so that it's easily accessible.

edit: PR: https://github.com/lxqt/pavucontrol-qt/pull/93

**Comment by palinek** [comment]
Go ahead and make a PR, but please make using/showing the tray icon configurable.

**Comment by tpruzina** [comment]
@palinek Not yet comfortable to submit a PR, been hacking on this a bit in my spare time but there are still few things that I'm missing - namely figuring out how mute/unmute output sinks on mouse click and how QEvent::Wheel works so that I could increase/decrease volume via mousewheel.

Other than that code needs some cleanup (moving non MainWindow code into separate class) and few UX bits (first time notification that window has closed to tray).

**Comment by tsujan** [comment]
The PR was closed "due to lack of interest and feedback."
